# Generated by Django 3.0.2 on 2020-01-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='imgsrc',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='exhibit_images'),
        ),
    ]
