# Generated by Django 3.0.2 on 2020-02-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200123_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='artifact_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='lookup_number',
            field=models.IntegerField(null=True),
        ),
    ]
