# Generated by Django 3.0.2 on 2020-02-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200203_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='video',
            field=models.FileField(default='default.mp4', upload_to='videos'),
        ),
    ]
