# Generated by Django 3.0.3 on 2020-02-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_exhibit_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='audio',
            field=models.FileField(default='default.mp3', upload_to='audio'),
        ),
    ]
