# Generated by Django 3.0.3 on 2020-02-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_exhibit_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
