# Generated by Django 3.0.2 on 2020-03-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_exhibit_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibit',
            old_name='artifact_number',
            new_name='accession_number',
        ),
        migrations.RenameField(
            model_name='exhibit',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='artist',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='date',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
