# Generated by Django 3.0.3 on 2020-03-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200302_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='additional_lookup_number',
            field=models.IntegerField(null=True),
        ),
    ]
