# Generated by Django 3.0.2 on 2020-03-09 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_exhibit_additional_lookup_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='additional_lookup_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Exhibit'),
        ),
    ]
